apiVersion: apps/v1
kind: Deployment
metadata:
  name: sewa-properti-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sewa-properti
  template:
    metadata:
      labels:
        app: sewa-properti
    spec:
      containers:
      - name: php-app
        image: rafly007/sewa-properti:v1
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql-db-service"
        - name: PORT
          value: "80"
        volumeMounts:
        - name: uploads-storage
          mountPath: /var/www/html/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sewa-properti-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: sewa-properti
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        args: ["--default-authentication-plugin=mysql_native_password"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "db_sewa_properti"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc